const MockUser = {
  "login": "taurusilver7",
  "id": 61942957,
  "node_id": "MDQ6VXNlcjYxOTQyOTU3",
  "avatar_url": "https://avatars.githubusercontent.com/u/61942957?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/taurusilver7",
  "html_url": "https://github.com/taurusilver7",
  "followers_url": "https://api.github.com/users/taurusilver7/followers",
  "following_url": "https://api.github.com/users/taurusilver7/following{/other_user}",
  "gists_url": "https://api.github.com/users/taurusilver7/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/taurusilver7/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/taurusilver7/subscriptions",
  "organizations_url": "https://api.github.com/users/taurusilver7/orgs",
  "repos_url": "https://api.github.com/users/taurusilver7/repos",
  "events_url": "https://api.github.com/users/taurusilver7/events{/privacy}",
  "received_events_url": "https://api.github.com/users/taurusilver7/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Devi prasad",
  "company": null,
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "A code enthusiast, beginner front-end developer, self-proclaimed photoshop designer.",
  "twitter_username": null,
  "public_repos": 13,
  "public_gists": 0,
  "followers": 3,
  "following": 21,
  "created_at": "2020-03-08T15:50:09Z",
  "updated_at": "2021-01-28T14:09:26Z"
  }

export default MockUser;